---

###############################################################
#
# General Playbook Variables
#

downloads: ~/.ansible-downloads/

###############################################################
#
# Homebrew - General Setup Variables
# Ansible Role: wayofdev.homebrew
#

homebrew_repository: https://github.com/Homebrew/brew
homebrew_repository_use_master: false
homebrew_write_global_path: true

homebrew_cask_greedy_mode: false
homebrew_upgrade_all: true

homebrew_clear_cache: false

homebrew_cask_appdir: /Applications

homebrew_retries: 3
homebrew_delay: 3

homebrew_collect_analytics: true

###############################################################
#
# Homebrew - Taps
# Ansible Role: wayofdev.homebrew
#

homebrew_taps:
  - homebrew/core
  - homebrew/cask
  - homebrew/cask-fonts

###############################################################
#
# Homebrew Packages
# Ansible Role: wayofdev.homebrew
#

homebrew_packages: []
#  - name: PackageName
#    state: present
#    update_homebrew: false

###############################################################
#
# Homebrew - Casks
# Ansible Role: wayofdev.homebrew
#

homebrew_casks: []
#  - name: CaskName
#    state: present

###############################################################
#
# Mac App Store (MAS) Application Variables
# Ansible Role: geerlingguy.mac.mas
#

mas_email: ""
mas_password: ""

mas_installed_apps: []
#  - { id: , name: "" }

mas_uninstalled_apps: []
#  - { id: , name: "" }

mas_upgrade_all_apps: false