---

###############################################################
#
# General Playbook Variables
#

downloads: ~/.ansible-downloads/

###############################################################
#
# Homebrew - General Setup Variables
# Ansible Role: wayofdev.homebrew
#

homebrew_repository: https://github.com/Homebrew/brew
homebrew_repository_use_master: false
homebrew_write_global_path: true

homebrew_cask_greedy_mode: false
homebrew_upgrade_all: true

homebrew_clear_cache: false

homebrew_cask_appdir: /Applications

homebrew_retries: 3
homebrew_delay: 3

homebrew_collect_analytics: true

###############################################################
#
# Homebrew - Taps
# Ansible Role: wayofdev.homebrew
#

homebrew_taps:
  - homebrew/core
    state: latest
  - homebrew/cask
    state: latest
  - homebrew/cask-fonts
    state: latest

###############################################################
#
# Homebrew Packages
# Ansible Role: wayofdev.homebrew
#

homebrew_packages: []
#  - name: PackageName
#    state: present
#    update_homebrew: false

###############################################################
#
# Homebrew - Casks
# Ansible Role: wayofdev.homebrew
#

homebrew_casks: []
#  - name: CaskName
#    state: present

###############################################################
#
# Mac App Store (MAS) Application Variables
# Ansible Role: geerlingguy.mac.mas
#

mas_email: ""
mas_password: ""

mas_installed_apps: []
#  - { id: , name: "" }

mas_uninstalled_apps: []
#  - { id: , name: "" }

mas_upgrade_all_apps: false

###############################################################
#
# macOS Dock Configuration Variables
# Ansible Role: geerlingguy.mac.dock
#

configure_dock: false

dockitems_remove: []
# Default macOS Dock Apps with macOS Ventura
#  - Launchpad
#  - Safari
#  - Messages
#  - Mail
#  - Maps
#  - Photos
#  - Facetime
#  - Calendar
#  - Contacts
#  - Reminders
#  - Notes
#  - Freeform
#  - TV
#  - Music
#  - 'App Store'
#  - 'System Settings'

dockitems_persist: []
#  - name: "App 1 Name"
#    path: "/Applications/App Name.app/"
#    pos: 1
#  - name: "App X Name"
#    path: "/Applications/App X Name.app/"
#    pos: X
