---

##############################################################
#
# General Playbook Variables
#

downloads: ~/.ansible-downloads/

################################################################
#
# Homebrew - General Setup Variables
# Ansible Role: geerlingguy.mac.homebrew
#

# Set this to your account password if casks need elevated privileges.
# ansible_become_password: ''

homebrew_repo: https://github.com/Homebrew/brew

homebrew_cask_appdir: /Applications
homebrew_cask_accept_external_apps: false

homebrew_folders_additional: []

homebrew_use_brewfile: true
homebrew_brewfile_dir: '~'

homebrew_clear_cache: false

homebrew_upgrade_all_packages: false

###############################################################
#
# Homebrew - Taps
# Ansible Role: geerlingguy.mac.homebrew
#

homebrew_taps: []

###############################################################
#
# Homebrew - Packages
# Ansible Role: geerlingguy.mac.homebrew
#

homebrew_installed_packages: []

homebrew_uninstalled_packages: []

################################################################
#
# Homebrew - Casks
# Ansible Role: geerlingguy.mac.homebrew
#

homebrew_cask_apps: []

homebrew_cask_uninstalled_apps: []

##############################################################
#
# Mac App Store (MAS) Application Variables
# Ansible Role: geerlingguy.mac.mas
#

mas_email: ""
mas_password: ""

mas_installed_apps: []
#  - { id: , name: "" }

mas_uninstalled_apps: []
#  - { id: , name: "" }

mas_upgrade_all_apps: false